GET http://localhost:5202/users

###
GET http://localhost:5202/users/1

###
POST http://localhost:5202/users
Content-Type: application/json

{
  "username": "new_user123",
  "passwordHash": "SuperSecretHash123",
  "email": "newuser@example.com",
  "userType": "CUSTOMER",
  "customerId": 305,
  "status": "ACTIVE"
}

###
PUT http://localhost:5202/users/3
Content-Type: application/json

{
  "username": "new_user123_updated",
  "passwordHash": "NewSecretHash456",
  "email": "updateduser@example.com",
  "userType": "CUSTOMER",
  "customerId": 305,
  "status": "LOCKED"
}

###
DELETE http://localhost:5202/users/3